README.md

There's a handful of secret generators already defined in `agenix-rekey.nix`.  This brings them into awareness via some README updates.  I did a cursory read on each of the various commands used and believe most are accurate if not very close descriptions of what they do, but please scrutinize this as some of them (like `dhparams`) I am not very familiar with.

document pre-defined secret generators

---

nix/package.nix

This allows tracing errors that occur when running `agenix`.  The actual error I've encountered is current immaterial because I believe it is resulting from other, experimental work.  But there is need to debug this work, and the current output is unhelpful (just showing built-in functions with no context).
Other arguments are accumulated and passed along to the subcommand, so there should be no discernible change in existing behavior, including if they previously used `--show-trace` (assuming `--show-trace` is after the subcommand).
Note that the placement of `--show-trace` is important.  If provided `--show-trace` before the subcommand, it applies to `agenix` itself.  If provided after the subcommand, it applies to the subcommand.  Some or all subcommands do not currently use …

add --show-trace to agenix CLI

---

apps/generate.nix

This simplifies the script a bit and fixes two problems:
1. we no longer add unrelated files that might be in the folder.
2. It might happen that the folder does not exist in which case the current script still tries to add it, in which case git will complain the it does not know the pathspec.

fix: only add deleted files to git

---

modules/agenix-rekey.nix

i use agenix and agenix-rekey with the `age-plugin-fido2-hmac` and `age-plugin-tpm` plugins which both produce files pointing to the hardware keystore.
this  setup works, but i have been getting warnings because my files had a `.hmac` suffix and i don't want to rename all of them, so i added this to the suffix list.
it might also be good to add documentation about options other than yubikeys because there are many other FIDO2 devices that are completely compatible.

added ".hmac" to the good suffix list

---

nix/lib.nix

Fix issue https://github.com/oddlama/agenix-rekey/pull/40 introduced.
Grep seems to consider path as a string and caused the error. This happened when having several `masterIdentities`.
**Haven't been tested** since I have no environment with Multiple keys.
https://github.com/oddlama/agenix-rekey/pull/40#discussion_r1753228726
Thanks @YourFin for reporting
---
Revert #40 and disabled the SC2043 shell check.

Revert #40 and disable SC2043 shellcheck

---

nix/package.nix

Related to #46, it seems this simple change makes it work. 
```
❯ nix run github:Toomoch/agenix-rekey/patch-1 -- --extra-flake-params \?submodules=1 rekey
Collecting information about hosts. This may take a while...
Skipping [already rekeyed] h81:duckdns
Skipping [already rekeyed] h81:secret1
```
A side effect is that with git submodules the `-a` flag does not work as expected:
```
❯ nix run github:Toomoch/agenix-rekey/patch-1 -- --extra-flake-params \?submodules=1 rekey -a
Collecting information about hosts. This may take a while...
warning: Git tree '/home/arnau/projects/nixos-config' is dirty
fatal: Pathspec '././private/secrets/rekeyed/b450' is in submodule 'private'
```
Everything else seems fine.

package: Add submodule support

---

nix/select-nodes.nix

In #51, I checked only for the presence of home-manager configurations but didn't verify if they had agenix-rekey enabled. Since adding home-manager configurations to nodes is enabled by default (see [flake.nix#L58](https://github.com/oddlama/agenix-rekey/blob/main/flake.nix#L58)), any home-manager configurations that don't include agenix-rekey will throw an error about a missing the .age attribute during the rekeying process.
Apologies for catching this issue only a few hours after the PR was accepted. I had tested it on a "dummy" configuration, but when applying it to my "real" dotfiles, I encountered the error.

fix: only add home-manager as a node if it has agenix-rekey enabled

---

examples/flake-parts/flake.nix
flake.nix

Commit cf28dcf rewrote the main `flake.nix` to use `flake-parts`, presumably without change for users, but there is actually one small regression there. The main flake's `perSystem` outputs' `system`s were reduced to only `["x86_64-linux" "aarch64-linux"]`, (accidentally) removing `["x86_64-darwin" "aarch64-darwin"]`.
This commit adds them back (both in the main flake and in the example)

fix(flake): re-add `{x86_64,aarch64}-darwin` to `flake-parts`'s systems

---

apps/rekey.nix

Note: This is just error enhancement.
When running `agenix rekey`, if a node (typically a host) doesn't have both `agenix` and `agenix-rekey` included as modules, you will see an error like this:
```
error: attribute 'age' missing
at /nix/store/zy9vgszqqqh51wmk8cjj6hghx6fydwbi-source/apps/rekey.nix:41:43:
40|
41|   nodesWithDerivationStorage = filter (x: x.config.age.rekey.storageMode == "derivation") (attrValues nodes);
|                                           ^
42|
```
This error doesn't tell you which host is missing the modules, let alone that the modules should be included.  The `agenix rekey` tool has this information available and can provide it upon encountering this issue.  These changes will detect the missing keys and halt with an error indicating which node is causing the …

indicate which node is missing agenix and agenix-rekey modules

---

nix/select-nodes.nix

I am attempting to migrate an existing  config to make use of the new home-manager support. I'm able to make use of the home-manager module, but the rekey CLI does not pick up my home-manager nodes. 
I was able to isolate the issue to `/nix/select-nodes.nix` in the repl:
```
nix-repl> :lf .
warning: Git tree '/home/dan/nixos' is dirty
Added 21 variables.
nix-repl> select-nodes = import ../Projects/agenix-rekey/nix/select-nodes.nix                                   
nix-repl> lib = inputs.nixpkgs.lib                                                                              
nix-repl> homeConfigurations = {}
nix-repl> collectHomeManagerConfigurations = true                                                              
nix-repl> select-nodes { inherit lib nixosConfigurations …
```

fix: improve check for home-manager nodes

---

README.md

The initial abstract was missing a link to the actual documentation.
While at it, remove a duplicated copy of the full description, the option documentation says the exact same. It is replaced by the initial abstract, which previously appeared before any major reference to the storage mode.

Streamline storage mode documentation

---

README.md

* Soft-recommend adding the plugin to the devShell.
* Public key can directly be added as a master identity since https://github.com/oddlama/agenix-rekey/pull/62

FIDO2 documentation tweaks

---

apps/edit.nix

Hello,
I tried to add a key to my `masterIdentities` and I found no other way to "rekey" everything except to run `agenix edit`. The script bails if the contents are unchanged, so it would have been painful to modify each file once and then undo the change with another `edit`.
This simple change makes this flow nicer, assuming that's the right way to do it.
Love the tool, thanks

Add --force to the edit command

---

flake.lock

Update git-hooks input after https://github.com/cachix/git-hooks.nix/pull/543 in order to remove a
redundant 'stable' nixpkgs.

Remove extra (stable) nixpkgs input.

---

apps/generate.nix

When trying to generate a secret using a secret without generator, an error occurred. And not the assert that was removed. The code was falling on `stringsWithDeps.textClosureMap` and I could not understand what the problem was. If add any generator - all fine.
After figuring it out, I first thought I could re-mark the assert, but I thought I could filter out the dependencies. This should not break the order of password generation, because filtered secrets have no dependencies.
Config:
```
{config, ...}: {
age.secrets.secret-1 = {
rekeyFile = ./secret-1.age;
};
age.secrets.secret-2 = {
rekeyFile = ./secret-2.age;
generator = {
dependencies = [
config.age.secrets.secret-1
];
script = {
pkgs,
lib,
decrypt,
deps,
...
}: ''
${decrypt} ${(lib.elemAt deps 0).file} \
| …
```

Fix generator with dependencies without generator

---

README.md
apps/edit.nix
apps/update-masterkeys.nix
flake-module.nix
flake.nix
nix/lib.nix
nix/package.nix

I received an additional yubikey yesterday, and to my surprise noticed that it's currently not possible to re-encrypt secrets with new/updated keys.
This PR adds a new subcommand, `update-masterkeys`, which simply decrypts, then re-encrypts all known secret files. I have also taken the liberty to move the `validRelativeSecretPaths` expression to the `lib`, since it's in use in multiple plasces now.

Add `update-masterkeys` subcommand

---

apps/generate.nix

`<<< "$var"` is the equivalent to `printf '%s\n' "$var"`.  This means we add an extra newline to our secrets as we encrypt them.  Many systems inspect their secret files literally, and interpret the newline as just another character in the secret (as opposed to a POSIX end-of-line+file).  This changes our encryption to use a `printf` expression that does not add a newline, and thus means we no longer mangle secrets emitted to disk.
This should have no impact on systems that filtered the newline in the first place.

do not add newlines in generated secrets

---

apps/generate.nix

`filter` doesn't accept lists, so attrset dependencies didn't actually work. Quick fix :)

fix: handle attrsets in ordering secrets

---

modules/agenix-rekey.nix

The new `secretDir` option acts like `generatedSecretsDir` for secrets that **are not** generated, permitting specifying such secret paths in relative form.
BREAKING CHANGE: brings the logic of `generatedSecretsDir` in line with its option description ("sets `age.secrets.<name>.rekeyFile` to a default value in this directory, for any secret that defines a generator"), whereas previously *all* secrets were expanded relative to `generatedSecretsDir` if it was defined.

`secretDir` option for specifying the default parent directory of non-generated secrets

---

apps/rekey.nix

fixes: #84
The `secretOut` was recently moved into `escapeShellArgs` which broke shell expansion and all secret wound up in `/tmp/"$UID"/XXX`
instead of `/tmp/1000/XXX`. This moves the secretOut back out so it will be expanded

fix: escaping Shell args prevents directory from being expanded

---

flake-module.nix

Added a filter to the default `nixosConfigurations` and `homeConfigurations` list options that checks if a given configuration contains the `age` module.

fix(flake-module): Added filtering for supported platforms

---

flake-module.nix

Fixes #111
Regression introduced in https://github.com/oddlama/agenix-rekey/commit/c4fd9281d31f8993635f39f04f3603b2d4fbf041
Side comment: should we also prepare for the (slow) migration from `{nixos,home}Configurations` -> `configurations.{nixos,home}` (same for `modules`)?

fix(flake-module): handle missing `homeConfigurations`

---

apps/rekey.nix
modules/agenix-rekey.nix

Allows for easier first deployment, without requiring an initial dummy rekeying.
See https://github.com/oddlama/agenix-rekey/issues/60

Produce placeholder secret and don't rekey when hostPubkey is dummy

---

apps/update-masterkeys.nix

`update-masterkeys` subcommand is having the same issue as `edit` used to.
`edit` was fixed in #101, doing the same thing for `update-masterkeys` here.

fix(update-masterkeys): use cp from coreutils
